yarnPath: .yarn/releases/yarn-2.4.1.cjs

# Failed to compile.
#
# Module not found: @aws-amplify/X tried to access @aws-amplify/Y, but it isn't declared in its dependencies;
# this makes the require call ambiguous and unsound.
packageExtensions:
  "@aws-amplify/api@*":
    dependencies:
      # ./.yarn/cache/@aws-amplify-api-npm-3.2.30-cfc9d17a70-ef156f3d1b.zip/node_modules/@aws-amplify/api/lib-esm/API.js
      "@aws-amplify/auth": "*"
      # idem
      "@aws-amplify/cache": "*"
      # idem
      "@aws-amplify/core": "*"
  "@aws-amplify/datastore@*":
    dependencies:
      # ./.yarn/cache/@aws-amplify-datastore-npm-2.9.16-25eb2e5416-04057925fb.zip/node_modules/@aws-amplify/datastore/lib-esm/sync/processors/subscription.js
      "@aws-amplify/auth": "*"
      # idem
      "@aws-amplify/cache": "*"
      # ./.yarn/cache/@aws-amplify-datastore-npm-2.9.16-25eb2e5416-04057925fb.zip/node_modules/@aws-amplify/datastore/lib-esm/util.js
      "crypto-js": "*"
  "@aws-amplify/storage@*":
    dependencies:
      # ./.yarn/cache/@aws-amplify-storage-npm-3.4.0-d253a241e3-d7248e6ddb.zip/node_modules/@aws-amplify/storage/lib-esm/providers/AWSS3ProviderManagedUpload.js
      "@aws-sdk/fetch-http-handler": "*"
      # ./.yarn/cache/@aws-amplify-storage-npm-3.4.0-d253a241e3-d7248e6ddb.zip/node_modules/@aws-amplify/storage/lib-esm/providers/axios-http-handler.js
      "@aws-sdk/protocol-http": "*"
      # idem
      "@aws-sdk/querystring-builder": "*"
  "@aws-amplify/ui-components@*":
    dependencies:
      # ./.yarn/$$virtual/@aws-amplify-ui-components-virtual-b697fad612/0/cache/@aws-amplify-ui-components-npm-1.2.0-93739495ef-1e8458e916.zip/node_modules/@aws-amplify/ui-components/dist/esm-es5/Translations-c833f663.js
      "@aws-amplify/auth": "*"
      # ./.yarn/$$virtual/@aws-amplify-ui-components-virtual-b697fad612/0/cache/@aws-amplify-ui-components-npm-1.2.0-93739495ef-1e8458e916.zip/node_modules/@aws-amplify/ui-components/dist/esm-es5/amplify-amazon-button_5.entry.js
      "@aws-amplify/core": "*"
      # ./.yarn/$$virtual/@aws-amplify-ui-components-virtual-b697fad612/0/cache/@aws-amplify-ui-components-npm-1.2.0-93739495ef-1e8458e916.zip/node_modules/@aws-amplify/ui-components/dist/esm-es5/amplify-chatbot.entry.js
      "@aws-amplify/interactions": "*"
      # ./.yarn/$$virtual/@aws-amplify-ui-components-virtual-b697fad612/0/cache/@aws-amplify-ui-components-npm-1.2.0-93739495ef-1e8458e916.zip/node_modules/@aws-amplify/ui-components/dist/esm-es5/amplify-s3-album.entry.js
      "@aws-amplify/storage": "*"
  "@aws-amplify/ui-react@*":
    dependencies:
      # ./.yarn/$$virtual/@aws-amplify-ui-react-virtual-3dde9c981e/0/cache/@aws-amplify-ui-react-npm-1.0.7-b3880dea19-346276e124.zip/node_modules/@aws-amplify/ui-react/lib-esm/withAuthenticator.js
      "@aws-amplify/auth": "*"
      # idem
      "@aws-amplify/core": "*"
